# Generated by Django 5.1.6 on 2025-02-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarParkingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=100, unique=True)),
                ('car_name', models.CharField(max_length=100)),
                ('inTime', models.DateTimeField(auto_now_add=True)),
                ('outTime', models.DateTimeField(auto_now=True)),
                ('totalSpendTime', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
