# Generated by Django 5.1.6 on 2025-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carparkingdetails',
            name='outTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
